{% set prefix = "spacy-model-" %}
{% set name = "en_core_web" %}
{% set version = "2.1.0" %}

package:
  name: {{ prefix }}{{ name|lower }}
  version: {{ version }}

source:
  - folder: sm
    url: https://github.com/explosion/spacy-models/releases/download/{{ name }}_sm-{{ version }}/{{ name }}_sm-{{ version }}.tar.gz
    sha256: 4db16860a8cdef56d436038ace6abeb9181a5176bdc8c16c755a20dced51e5f1
  - folder: md
    url: https://github.com/explosion/spacy-models/releases/download/{{ name }}_md-{{ version }}/{{ name }}_md-{{ version }}.tar.gz
    sha256: b84c7e5d57840d6ad9160cfb746ebffde0c5fd04ee69ddfaa1ed36d37ac06f83
  - folder: lg
    url: https://github.com/explosion/spacy-models/releases/download/{{ name }}_lg-{{ version }}/{{ name }}_lg-{{ version }}.tar.gz
    sha256: a260a236354a4cac47ff1260c84ee4cb980249f947753bb9bbb56b9bda678c7b
  - url: https://creativecommons.org/licenses/by-sa/3.0/legalcode.txt
    sha256: 3f941b3b89cf7b8370ceb83cc76d2120d471b58735d8ca60238a751a48d7f72f

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - setuptools
    - python

test:
  commands:
    - echo "make lint happy"

outputs:
  - name: {{ prefix }}{{ name }}_{{ size }}
    build:
      noarch: python
      number: 0
      script: cd {{ size }} && {{ PYTHON }} -m pip install . --no-deps -vv
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - setuptools
    test:
      imports:
        - {{ name }}_{{ size }}
      requires:
        - spacy {{ version.split('.')[0] }}.*
      commands:
        - python -c "__import__('{{ name }}_{{ size }}').load()"
        - python -c "__import__('spacy').load('{{ name }}_{{ size }}')"

about:
  home: https://spacy.io
  license: CC BY-SA 3.0
  summary: 'English multi-task CNN trained on OntoNotes, with GloVe vectors trained on Common Crawl.'
  license_file: legalcode.txt

  doc_url: https://spacy.io/models/en
  dev_url: https://github.com/explosion/spacy-models

extra:
  recipe-maintainers:
    - sodre
    - bollwyvl
