{% set prefix = "spacy-model-" %}
{% set name = "en_core_web_" %}
{% set version = "3.1.0" %}
{% set build_number = 0 %}
# see https://github.com/explosion/spacy-models/blob/master/compatibility.json
# but the pattern _generally_ seems to be x.x
{% set spacy_version = ".".join(version.split(".")[:2] + ['*']) %}

package:
  name: {{ prefix }}{{ name[:-1] }}
  version: {{ version }}

source:
  - url: https://github.com/explosion/spacy-models/releases/download/{{ name }}sm-{{ version }}/{{ name }}sm-{{ version }}.tar.gz
    sha256: f624cbee5511e6c90e4ff9ed502c8acab14bf82096c0e28a4645564b70f87660
    folder: sm
  - url: https://github.com/explosion/spacy-models/releases/download/{{ name }}md-{{ version }}/{{ name }}md-{{ version }}.tar.gz
    sha256: 7f0de3a2a7b6d6e17ce75188a7ec227c2283dc2df010ee5e0905096335d7c594
    folder: md
  - url: https://github.com/explosion/spacy-models/releases/download/{{ name }}lg-{{ version }}/{{ name }}lg-{{ version }}.tar.gz
    sha256: be75145932fad6f496eb3cd2f9c09152ad34b286507406d23200a70c0c88d580
    folder: lg
  - url: https://raw.githubusercontent.com/explosion/spaCy/master/LICENSE
    sha256: b90775797175e7aa165a5508c8132da463b8ae029b419f4fc52450276d9f2872

build:
  noarch: python
  number: {{ build_number }}

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - setuptools
    - python >=2.7

test:
  commands:
    - echo "make lint happy"

outputs:
  - name: {{ prefix }}{{ name }}sm
    files:
      - sm
      - LICENSE
    build:
      noarch: python
      number: {{ build_number }}
      script: cd sm && {{ PYTHON }} -m pip install . --no-deps -vv
    requirements:
      host:
        - python >=2.7
        - pip
      run:
        - python >=2.7
        - setuptools
      run_constrained:
        - spacy =={{ spacy_version }}
    test:
      imports:
        - {{ name }}sm
      requires:
        - spacy
      commands:
        - python -c "__import__('{{ name }}sm').load()"
        - python -c "__import__('spacy').load('{{ name }}sm')"

  - name: {{ prefix }}{{ name }}md
    files:
      - md
      - LICENSE
    build:
      noarch: python
      number: {{ build_number }}
      script: cd md && {{ PYTHON }} -m pip install . --no-deps -vv
    requirements:
      host:
        - python >=2.7
        - pip
      run:
        - python >=2.7
        - setuptools
      run_constrained:
        - spacy =={{ spacy_version }}
    test:
      imports:
        - {{ name }}md
      requires:
        - spacy
      commands:
        - python -c "__import__('{{ name }}md').load()"
        - python -c "__import__('spacy').load('{{ name }}md')"

  - name: {{ prefix }}{{ name }}lg
    files:
      - lg
      - LICENSE
    build:
      noarch: python
      number: {{ build_number }}
      script: cd lg && {{ PYTHON }} -m pip install . --no-deps -vv
    requirements:
      host:
        - python >=2.7
        - pip
      run:
        - python >=2.7
        - setuptools
      run_constrained:
        - spacy =={{ spacy_version }}
    test:
      imports:
        - {{ name }}lg
      requires:
        - spacy
      commands:
        - python -c "__import__('{{ name }}lg').load()"
        - python -c "__import__('spacy').load('{{ name }}lg')"

about:
  home: https://spacy.io
  license: MIT
  license_file: LICENSE
  summary: English multi-task CNN trained on OntoNotes, with GloVe vectors trained on Common Crawl.
  doc_url: https://spacy.io/models/en
  dev_url: https://github.com/explosion/spacy-models

extra:
  recipe-maintainers:
    - sodre
    - bollwyvl
    - setu4993
