{% set prefix = "spacy-model-" %}
{% set name = "en_core_web_" %}
{% set version = "3.0.0" %}

package:
  name: {{ prefix|lower }}{{ name[:-1]|lower }}
  version: {{ version }}

source:
  - url: https://github.com/explosion/spacy-models/releases/download/{{ name }}sm-{{ version }}/{{ name }}sm-{{ version }}.tar.gz
    sha256: 0673b3ce4a28a19e99dc0fc3f8f7fe67b936c41749e6b70f778ec5f9f78f3a66
    folder: sm
  - url: https://github.com/explosion/spacy-models/releases/download/{{ name }}md-{{ version }}/{{ name }}md-{{ version }}.tar.gz
    sha256: 45757583a3c9d15c6895cf4bf9512e86243bab8cda51512c127f5cbdc34ac630
    folder: md
  - url: https://github.com/explosion/spacy-models/releases/download/{{ name }}lg-{{ version }}/{{ name }}lg-{{ version }}.tar.gz
    sha256: 1eb1fafcde97778bc3c13f9da712e37d789f5d1bc2f3314968222cb77f41ab69
    folder: lg
  - url: https://raw.githubusercontent.com/explosion/spaCy/master/LICENSE
    sha256: b90775797175e7aa165a5508c8132da463b8ae029b419f4fc52450276d9f2872

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - setuptools
    - python

test:
  commands:
    - echo "make lint happy"

outputs:
  - name: {{ prefix }}{{ name }}sm
    files:
      - sm
      - LICENSE
    build:
      noarch: python
      number: 0
      script: cd sm && {{ PYTHON }} -m pip install . --no-deps -vv
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - setuptools
    test:
      imports:
        - {{ name }}sm
      requires:
        - spacy {{ version.split('.')[0] }}.{{ version.split('.')[1] }}.*
      commands:
        - python -c "__import__('{{ name }}sm').load()"
        - python -c "__import__('spacy').load('{{ name }}sm')"
  - name: {{ prefix }}{{ name }}md
    files:
      - md
      - LICENSE
    build:
      noarch: python
      number: 0
      script: cd md && {{ PYTHON }} -m pip install . --no-deps -vv
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - setuptools
    test:
      imports:
        - {{ name }}md
      requires:
        - spacy {{ version.split('.')[0] }}.{{ version.split('.')[1] }}.*
      commands:
        - python -c "__import__('{{ name }}md').load()"
        - python -c "__import__('spacy').load('{{ name }}md')"
  - name: {{ prefix }}{{ name }}lg
    files:
      - lg
      - LICENSE
    build:
      noarch: python
      number: 0
      script: cd lg && {{ PYTHON }} -m pip install . --no-deps -vv
    requirements:
      host:
        - python
        - pip
      run:
        - python
        - setuptools
    test:
      imports:
        - {{ name }}lg
      requires:
        - spacy {{ version.split('.')[0] }}.{{ version.split('.')[1] }}.*
      commands:
        - python -c "__import__('{{ name }}lg').load()"
        - python -c "__import__('spacy').load('{{ name }}lg')"

about:
  home: https://spacy.io
  license: MIT
  license_file: LICENSE
  summary: English multi-task CNN trained on OntoNotes, with GloVe vectors trained on Common Crawl.
  doc_url: https://spacy.io/models/en
  dev_url: https://github.com/explosion/spacy-models

extra:
  recipe-maintainers:
    - sodre
    - bollwyvl
    - setu4993
