# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_sizelg
    - CONFIG=osx_sizemd
    - CONFIG=osx_sizesm

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "DRNaynl/UAj46l1CEd9stSgCrvqWEIM873IMChKXYQIbHrtzJHdRzXUIgNyIARVeokrlGXFXWvkDBR13wMzpaddcgktoJCkxfx1mAzOXfnlgoCu3xKsoCqCojqo0Y/WM9G35Ad/8lE5tOjBwvs1oLmC8QmYfM1778ZUGR5UrBE05s6DYTMyfpSEiQNF5opJpI6W19hEsB1pJfa970OzFAc4iVdKrYiCqA0ufygjv2+STfrsSIhp/0B9n04b+8wtfJsjvN1DHZEAEhAqPka6ntatAxJGV+bfSEkWHf5Ngp6ZeLo5T84u8rhNGd2myuVG9F4LzX9/VVWlmoYy0MR0x+Z6z8b9SGFOje/M8/ahZ1voSxvnbwhFNyC50MzeLiaoODCtUD0KaLHExEBBSeUMFOCsBUzEaZEELZ+h0yVZRAxTJDDQep4qXgQWca8blyh9uxoSEvST9Gs7ge+I7mRMR/OI1yGy16Gq24yLICC66g0tvcu2D6vzlqHD+rM/ZlvLIEvo4ZwcxvyFfl09kth+Fw4zEPxJN+/+I/BKozKijeGw1Amy3QUIIIHkzae9x76xRllTh8/go/gjzA02fP8Hn7UcWbqGcc1Qkg8aex7oRAD+seYNvSAasU0U/HMkBxhMmdnaFZw99p8ft5L1pgAjYHNvXj+qicl/UBdXUe5xjKAc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml