travis:
  secure:
    BINSTAR_TOKEN: DRNaynl/UAj46l1CEd9stSgCrvqWEIM873IMChKXYQIbHrtzJHdRzXUIgNyIARVeokrlGXFXWvkDBR13wMzpaddcgktoJCkxfx1mAzOXfnlgoCu3xKsoCqCojqo0Y/WM9G35Ad/8lE5tOjBwvs1oLmC8QmYfM1778ZUGR5UrBE05s6DYTMyfpSEiQNF5opJpI6W19hEsB1pJfa970OzFAc4iVdKrYiCqA0ufygjv2+STfrsSIhp/0B9n04b+8wtfJsjvN1DHZEAEhAqPka6ntatAxJGV+bfSEkWHf5Ngp6ZeLo5T84u8rhNGd2myuVG9F4LzX9/VVWlmoYy0MR0x+Z6z8b9SGFOje/M8/ahZ1voSxvnbwhFNyC50MzeLiaoODCtUD0KaLHExEBBSeUMFOCsBUzEaZEELZ+h0yVZRAxTJDDQep4qXgQWca8blyh9uxoSEvST9Gs7ge+I7mRMR/OI1yGy16Gq24yLICC66g0tvcu2D6vzlqHD+rM/ZlvLIEvo4ZwcxvyFfl09kth+Fw4zEPxJN+/+I/BKozKijeGw1Amy3QUIIIHkzae9x76xRllTh8/go/gjzA02fP8Hn7UcWbqGcc1Qkg8aex7oRAD+seYNvSAasU0U/HMkBxhMmdnaFZw99p8ft5L1pgAjYHNvXj+qicl/UBdXUe5xjKAc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
